name: Turn Feature Flag ON / OFF

on:
  workflow_dispatch:
    inputs:
      flag_key:
        description: 'Feature flag key'
        required: true
        type: string
      flag_update:
        description: 'Update Feature Flag to On/Off'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
      environment: 
        description: 'Update to Test/Production'
        required: true
        type: choice
        options: 
          - 'test'
          - 'production'

jobs:
  create-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Update Feature Flag via LaunchDarkly API
        env:
          LD_API_KEY: ${{ secrets.LAUNCHDARKLY_API_KEY }}
        run: |
          # Set the flag value based on input
          FLAG_KEY="${{ github.event.inputs.flag_key }}"
          FLAG_VALUE="${{ github.event.inputs.flag_update }}"
          LD_PROJECT_KEY="${{ secrets.LAUNCHDARKLY_PROJECT_KEY }}"
          LD_ENV_KEY="${{ github.event.inputs.environment }}"

          # Build the JSON payload for the patch
          jq -n --argjson value "${FLAG_VALUE}" '{patch: [{op: "replace", path: "/environments/'"${LD_ENV_KEY}"'/on", value: $value}]}' > patch.json

          # Make the API call to update the flag
          curl -X PATCH "https://app.launchdarkly.com/api/v2/flags/${LD_PROJECT_KEY}/${FLAG_KEY}" \
            -H "Authorization: $LD_API_KEY" \
            -H "Content-Type: application/json" \
            -d @patch.json
            