name: Check Feature Flag Toggle Status - ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      flag_key:
        description: 'Feature flag key'
        required: true
        type: string
      environment: 
        description: 'Update to Test/Production'
        required: true
        type: choice
        options: 
          - 'test'
          - 'production'

jobs:
  create-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Get and Display Feature Flag Status via LaunchDarkly API
        env:
          LD_API_KEY: ${{ secrets.LAUNCHDARKLY_API_KEY }}
        run: |
          # Set the flag value based on input
          FLAG_KEY="${{ github.event.inputs.flag_key }}"
          LD_PROJECT_KEY="${{ secrets.LAUNCHDARKLY_PROJECT_KEY }}"
          LD_ENV_KEY="${{ github.event.inputs.environment }}"

          # Make the API call to get the flag status
          RESPONSE=$(curl -s "https://app.launchdarkly.com/api/v2/flag-statuses/${LD_PROJECT_KEY}/${LD_ENV_KEY}/${FLAG_KEY}" \
            -H "Authorization: $LD_API_KEY")

          # Parse the response to get the flag status (requires jq)
          STATUS=$(echo "$RESPONSE" | jq -r '.name')

          # Write the status to the GitHub Actions job summary
          echo "### LaunchDarkly Flag Status" >> $GITHUB_STEP_SUMMARY
          echo "Flag: $FLAG_KEY" >> $GITHUB_STEP_SUMMARY
          echo "Environment: $LD_ENV_KEY" >> $GITHUB_STEP_SUMMARY
          echo "Status: $STATUS" >> $GITHUB_STEP_SUMMARY

          # Optionally, print to log as well
          echo "Flag status: $STATUS"
            