name: Check Feature Flag Toggle Status

on:
  workflow_dispatch:
    inputs:
      flag_key:
        description: 'Feature flag key'
        required: true
        type: string
      environment: 
        description: 'Update to Test/Production'
        required: true
        type: choice
        options: 
          - 'test'
          - 'production'

jobs:
  create-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Update Feature Flag via LaunchDarkly API
        env:
          LD_API_KEY: ${{ secrets.LAUNCHDARKLY_API_KEY }}
        run: |
          # Set the flag value based on input
          FLAG_KEY="${{ github.event.inputs.flag_key }}"
          LD_PROJECT_KEY="${{ secrets.LAUNCHDARKLY_PROJECT_KEY }}"
          LD_ENV_KEY="${{ github.event.inputs.environment }}"

          # Make the API call to update the flag
          curl "https://app.launchdarkly.com/api/v2/flag-statuses/${LD_PROJECT_KEY}/${LD_ENV_KEY}/${FLAG_KEY}" \
            -H "Authorization: $LD_API_KEY" 
            